# config.make generated by configure script
POCO_CONFIG = MinGW
POCO_BASE = /e/Projects/Arm/download/poco-1.7.6
POCO_BUILD = /e/Projects/Arm/download/poco-1.7.6
POCO_FLAGS =  -DPOCO_NO_SHAREDLIBS -DPOCO_NO_SHAREDLIBS
POCO_PREFIX = /usr/local
OMIT = Data/ODBC Data/MySQL MongoDB PDF CppParser
LINKMODE = STATIC
export POCO_CONFIG
export POCO_BASE
export POCO_BUILD
export POCO_FLAGS
export POCO_PREFIX
export LINKMODE
