TrajectoryPlannerROS:
  # we can strafe
  holonomic_robot: true
  
  # robot speed and acceleration limits
  min_in_place_vel_theta: 0.0
  y_vels: [-0.1, -0.09, -0.08,-0.07,-0.06,-0.05,-0.04,-0.03,-0.02,-0.01, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ]

  max_vel_theta: 0.3
  min_vel_theta: -0.3
  escape_vel: -0.100    # use negative value to escape, otherwise bot runs forward when escaping
  max_vel_x: 0.100      # maximum forward velocity in [m/s]
  min_vel_x: -0.100
  max_vel_y: 0.100      # max strafing speed
  min_vel_y: -0.100     # 
  acc_lim_theta: 0.1
  acc_lim_x: 0.05
  acc_lim_y: 0.05
  
  latch_xy_goal_tolerance: true
  sim_time: 1.0
  dwa: false
  oscillation_reset_dist: 10.00
  heading_lookahead: 1.0

controller_frequency: 5 # same like publish frequency of local planner

# Default recover behaviour is rotating a lot, which is quite useless for a holonomic robot
clearing_rotation_allowed: false
recovery_behaviors: [{name: aggressive_reset, type: clear_costmap_recovery/ClearCostmapRecovery}]
#                   [{name: rotate_recovery, type: rotate_recovery/RotateRecovery}, 
#                   [{name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery}]