TrajectoryPlannerROS:
  # we can strafe
  holonomic_robot: true
  
  # robot speed and acceleration limits
  min_in_place_vel_theta: 0.0
  y_vels: -0.1, -0.08,-0.06, -0.04, -0.02, -0.01,0.01, 0.02, 0.04, 0.06 0.08, 0.1 
  max_vel_theta: 0.2
  min_vel_theta: -0.2
  escape_vel: -0.100    # use negative value to escape, otherwise bot runs forward when escaping
  max_vel_x: 0.100      # maximum forward velocity in [m/s]
  min_vel_x: -0.100
  max_vel_y: 0.100      # max strafing speed
  min_vel_y: -0.100     # 
  acc_lim_theta: 0.06
  acc_lim_x: 0.06
  acc_lim_y: 0.06

  
controller_frequency: 5 # same like publish frequency of local planner
