# circular footprint radius of the pentapod
robot_radius: 0.350
# timing tolerance of transformation in [s] 
transform_tolerance: 0.30
map_type: costmap
obstacle_layer:
  enabled: true
  # the maximum range sensor reading that will result in an obstacle being put into the costmap
  obstacle_range: 2.5  
  # determines the range to which we will raytrace freespace given a sensor reading
  raytrace_range: 4.0
  # do not go in unknown space
  track_unknown_space: false
  combination_method: 1
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}
inflation_layer:
  enabled: true
  cost_scaling_factor: 5.0 
  # The inflation radius should be set to the maximum distance from obstacles 
  inflation_radius: 1.00
static_layer:
  enabled: true
  map_topic: /map

