scan_topic: scan
base_frame: base_link
odom_frame: base_link

output_timing: false
advertise_map_service: true
use_tf_scan_transformation: true
use_tf_pose_start_estimate: false
pub_map_odom_transform: false
map_with_known_poses: false

map_pub_period: 2.0
map_update_distance_thresh: 0.05   # after moving 0.05m SLAM jumps in
map_update_angle_thresh: 0.1

# Map size and resolution
map_resolution: 0.05
map_size: 512

# Laser limits. Lidar starts at 0.4m, 
# but knee can reach 0.45m so in case a knee blocks the sight do
# not consider that as an obstacle
laser_max_dist: 8.0                 
laser_min_dist: 0.45
    
