local_costmap:
  # circular footprint radius of the pentapod
  # in the local map we use a smaller radius than in the global to prevent that the robot is stuck in lethal locations close to a wall.  
  robot_radius: 0.20
  
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0    # lidar delivers scans with 10Hz
  publish_frequency: 2.0 
  static_map: false
  # Setting the "rolling_window" parameter to true means that the costmap 
  # will remain centered around the robot as the robot moves through the world
  rolling_window: True
  width: 2.0
  height: 2.0
  resolution: 0.05
  transform_tolerance: 0.5   # tolerable tf latency
  always_send_full_costmap: true
plugins:
- {name: static_layer, type: "costmap_2d::StaticLayer"}
- {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
